// Shared types for Tab Garden landing page.

export type IconName =
  | "layout-grid"
  | "clock"
  | "cloud-sync"
  | "timer"
  | "search-check"
  | "shield-check"
  | "lock"
  | "mail"
  | "chrome"
  | "globe"
  | "layers"
  | "copy-x"
  | "bookmark"
  | "briefcase"
  | "refresh"
  | "download"
  | "sparkles"
  | "mouse-pointer"
  | "monitor"
  | "check"
  | "arrow-right"
  | "menu"
  | "x"
  | "github"
  | "star"
  | "zap"
  | "eye"
  | "ban"
  | "key";
